import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Vertex L Shape LH Sofa",
    sub_title: "Fabric + Syn Leather, Dark Grey",
    offer_price: "71499", 
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647523472/sofas/56101502SD01662_02_803x602_hapxps.png",
    price: "76900",
    description: "The high back sofa offers firm lumbar support which facilities comfortable upright or casual seating.",
    categoryName: "Sofas",
    rating: "5",
  },
  {
    _id: uuid(),
    title: "Cyan L Shape Sofa",
    sub_title: "Fabric, Blue",
    offer_price: "51999", 
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647523610/sofas/56101502SD00927_02_803x602_atx9pk.png",
    price: "55710",
    description: "A simple yet sophisticated blue fabric best suits formal living rooms and contemporarily styled decors, adds a soft touch to your urban living space.",
    categoryName: "Sofas",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Arcade L Shape Sofa",
    sub_title: "Fabric, Denim",
    offer_price: "75000", 
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647523550/sofas/56101502SD01672_02_803x602_hdy3lr.png",
    price: "82000",
    description: "The broad seating space and longer length of the 3-seater make it an ideal place for napping or relaxed lounging.",
    categoryName: "Sofas",
    rating: "5",
  },
  {
    _id: uuid(),
    title: "Coffee Table",
    sub_title: "Tempered Glass, Black",
    offer_price: "19499",
    img: "https://www.godrejinterio.com/imagestore/B2C/56121403SD00032/56121403SD00032_01_803x602.png",
    price: "20499",
    description: "The coffee table is a versatile piece of furniture that can be used for a variety of purposes.",
    categoryName: "Tables",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "Aero King Size Bed With Storage",
    sub_title: "Engineered Wood, Oak",
    offer_price: "105000",
    img: "https://www.godrejinterio.com/imagestore/B2C/56101515SD00220/56101515SD00220_01_803x602.png",
    price: "125000",
    description: "The king size bed is a versatile piece of furniture that can be used for a variety of purposes.",
    categoryName: "Beds",
    rating: "5",
  },
  {
    _id: uuid(),
    title: "Motion High Back Chair",
    sub_title: "Engineered Wood, Oak",
    offer_price: "8900",
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647537227/chairs/56101522SD03673_01_803x602_khd4jx.png",
    price: "11900",
    description: "The unique design construction allows flexing and spring-back motion enabling multi-dimensional movement to suit body posture.",
    categoryName: "Chairs",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Linea Sliding Door Wardrobe",
    sub_title: "2 Door, Rustic Almond",
    offer_price: "57490",
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647523215/56101509SD00462_01_803x602_gjsp9v.png",
    price: "65000",
    description: "The sliding wardrobe is a versatile piece of furniture that can be used for a variety of purposes.",
    categoryName: "Wardrobes",
    rating: "4"
  },
  {
    _id: uuid(),
    title: "Slimline 2 Door steel Wardrobe",
    sub_title: "Locker, Pac Blue Color",
    offer_price: "24500",
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647523112/SLIM00074_01_803x602_zugiyz.png",
    price: "27000",
    description: "The sliding wardrobeThe furniture with which you furnish your home reflects your style and sensibilities.",
    categoryName: "Wardrobes",
    rating: "4"
  },
  {
    _id: uuid(),
    title: "Slimline 2 Door steel Wardrobe",
    sub_title: "Locker, Pac Blue Color",
    offer_price: "56000",
    img: "https://www.godrejinterio.com/imagestore/B2C/SQ02DROHU/SQ02DROHU_01_803x602.png",
    price: "59900",
    description: "The sliding wardrobeThe furniture with which you furnish your home reflects your style and sensibilities.",
    categoryName: "Wardrobes",
    rating: "3"
  },
  
  {
    _id: uuid(),
    title: "Colloseum L Shape Sofa",
    sub_title: "Fabric, Dark Red",
    offer_price: "61999", 
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647523517/sofas/56101502SD01658_02_803x602_kxyib5.png",
    price: "64715",
    description: "The sofa is low back in smooth rounded forms with firm support. The firm back supports facilities upright seating or casual seating.",
    categoryName: "Sofas",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "Liux Bar Chair",
    sub_title: "Set of 2, Blue",
    offer_price: "14490",
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647537193/chairs/DINCHR078_01_803x602_cw66yb.png", 
    price: "19500",
    description: "The slightly curved backrest provides support to your back, allowing you or your loved ones to continue conversations for longer periods of time",
    categoryName: "Chairs",
    rating: "4"
  },
  {
    _id: uuid(),
    title: "Utopia King Bed",
    sub_title: "Natural Brown, Sheesham",
    offer_price: "107000",
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647522688/56101515SD00324_01_803x602_lwnrgl.png",
    price: "125000",
    description: "Due to the well-defined grain of Rosewood, each piece of the Utopia King Bed is unique in coloring, making your bed distinct.",
    categoryName: "Beds",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Chocolate Study Table",
    sub_title: "Chocolate, Black",
    offer_price: "22490",
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647537472/tables/56101597SD00016_01_803x602_mm3ggh.png",
    price: "25000",
    description: "The wide berth of the table top can hold everything from your laptop to your books and that too, at the same time!",
    categoryName: "Tables",
    rating: "4"
  },
  {
    _id: uuid(),
    title: "Aero High Back Synchro Chair",
    sub_title: "Adjustable Armrest, Black",
    offer_price: "13490",
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647537153/chairs/AERO0001_01_803x602_o13ln0.png", 
    price: "14800",
    description: "The slightly curved backrest provides support to your back, allowing you or your loved ones to continue conversations for longer periods of time",
    categoryName: "Chairs",
    rating: "3"
  },
  {
    _id: uuid(),
    title: "Greta Mid Back Mesh Chair",
    sub_title: "Fabric, Grey Mesh With White Body",
    offer_price: "18200",
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647537265/chairs/56101522SD02032_01_803x602_wp0ckc.png",
    price: "19900",
    description: "The chair strikes a perfect balance between indisputable functionality and striking aesthetics.",
    categoryName: "Chairs",
    rating: "3"
  },
  {
    _id: uuid(),
    title: "Prime High Back Chair",
    sub_title: "Fabric, Black",
    offer_price: "15800",
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647537299/chairs/ELITE0001_1_803x602_uqpst6.png",
    price: "17000",
    description: "The chair strikes a perfect balance between indisputable functionality and striking aesthetics.",
    categoryName: "Chairs",
    rating: "4"
  },
  {
    _id: uuid(),
    title: "WFH Table",
    sub_title: "Slam Teak Wood",
    offer_price: "8400",
    img: "https://res.cloudinary.com/furnhouse/image/upload/v1647537512/tables/56101519SD01213_02_803x602_baeso3.png",
    price: "9999",
    description: "The Upbeat table can be pushed to any part of your home to get that best location from where positive work can happen.",
    categoryName: "Tables",
    rating: "2"
  },  
];
